import { Libre_Baskerville } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import NextAuthSessionProvider from "@/Providers/NextAuthSessionProvider";

const libreBaskerville = Libre_Baskerville({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <NextAuthSessionProvider>
          <body className={`${libreBaskerville.className} antialiased`}>
            {children}
          </body>
        </NextAuthSessionProvider>
      </ThemeProvider>
    </html>
  );
}